theme: jekyll-theme-minimal
title: PuntComa
description: AI of the Future
logo: [Location of the logo]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: UA-119195086-2
