theme: jekyll-theme-minimal
title: PuntComa
description: AI of the Future
logo: https://github.com/Dreitser/PuntComaSite1/blob/master/PuntComaLogo.jpg
show_downloads: "false"
google_analytics: UA-119195086-2
